import ShoppingCart from "@/components/templates/ShoppingCart";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <ShoppingCart />
    </>
  );
}
